### ISSUE TITLE
10.3389/fgene.2020.610798

### ISSUE THREAD

**Issue by krassowski** [leipzig/awesome-reproducible-research#53]
Thank you for the list! We included a text-mining based census of 1857 abstracts + 1520 full text articles discussing multi-omics, which included a look at deposition of data and software (in short we were not impressed with the adoption rates of Dryad/OSF/Zenodo, though this seems to be better with software repositories like GitHub/Bioconductor/PyPI or CRAN).

As it was not our prime focus, there may be false positives, so I describe it as a higher bound for repositories that were mentioned in papers rather than an accurate estimate though. I hope it may help someone who is looking at things like that in more detail.

Repository: https://github.com/krassowski/multi-omics-state-of-the-field.

Don't know if relevant/awesome enough for the list though.

**Comment by leipzig** [comment]
added. thanks!
