### ISSUE TITLE
Update for the Haibe-Kains Lab

### ISSUE THREAD

**Issue by bhaibeka** [leipzig/awesome-reproducible-research#72]
Hi,

We have been publishing additional studies that have been made fully reproducible via Code Ocean, you can find the complete list here:

https://docs.google.com/document/d/1zddn2Vy-hNZ9ad1dTAt9QCLCZYMLHNhCcGrUEJwZSSk/edit?usp=sharing

Thanks for your work!

**Comment by leipzig** [comment]
done. for my notes:

python src/doi2md.py --type codeocean --capsule 354235 --doi 10.1093/bib/bbab294
python src/doi2md.py --type codeocean --capsule 7358839 --doi 10.1093/bib/bbab294
python src/doi2md.py --type codeocean --capsule 2097894 --doi 10.1016/j.phro.2021.04.001
python src/doi2md.py --type codeocean --capsule 8791617 --doi 10.1038/s41467-021-21233-0
python src/doi2md.py --type codeocean --capsule 2817911 --doi 10.1101/2020.09.08.287573
python src/doi2md.py --type codeocean --capsule 6911149 --doi 10.1038/s41467-020-20830-9
python src/doi2md.py --type codeocean --capsule 6322807 --doi 10.1093/nar/gkaa421
python src/doi2md.py --type codeocean --capsule 6718332 --doi 10.1038/s41597-019-0174-7
python src/doi2md.py --type codeocean --capsule 1166221 --doi 10.1158/0008-5472.CAN-19-0179
python src/doi2md.py --type codeocean --capsule 0002901 --doi 10.1101/222562
python src/doi2md.py --type codeocean --capsule 0544852 --doi 10.1093/bioinformatics/btz485
python src/doi2md.py --type codeocean --capsule 0566399 --doi 10.1158/0008-5472.CAN-19-0349
python src/doi2md.py --type codeocean --capsule 0795540 --doi 10.1007/978-981-32-9816-3_19
python src/doi2md.py --type codeocean --capsule 7402260 --doi 10.1200/CCI.18.00102
python src/doi2md.py --type codeocean --capsule 6438633 --doi 10.1101/052910
python src/doi2md.py --type codeocean --capsule 5502756 --doi 10.1093/jamia/ocx062
python src/doi2md.py --type codeocean --capsule 0002901 --doi 10.1038/s41467-017-01153-8
python src/doi2md.py --type codeocean --capsule 4252248 --doi 10.1158/0008-5472.CAN-17-0096
python src/doi2md.py --type codeocean --capsule 6276064 --doi 10.12688/f1000research.9611.3

**Comment by leipzig** [comment]
amazing catalogue
