### ISSUE TITLE
thesis/dissertation section

### ISSUE THREAD

**Issue by leipzig** [leipzig/awesome-reproducible-research#81]
I am considering adding a section for theses/dissertations on reproducibility. I suppose with links to Proquest?

@atrisovic will include yours - lemme know if you have others in mind

**Comment by atrisovic** [comment]
Sounds good to me! I will post here or create a PR if/when others pop to mind.

**Comment by nuest** [comment]
Is it alright to self-nominate ? https://zenodo.org/record/4768096

@MarkusKonk also has https://doi.org/10.31237/osf.io/mcdrn
