### ISSUE TITLE
stuff from that ml repro article

### ISSUE THREAD

**Issue by leipzig** [leipzig/awesome-reproducible-research#98]
https://www.nature.com/articles/s42256-021-00307-0
https://pubs.rsna.org/doi/10.1148/ryai.2020200029
https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2781307
https://www.science.org/doi/10.1126/scitranslmed.abb1655

**Comment by Emiller88** [comment]
This might also be interesting https://www.mlf-core.com/index
